### ISSUE TITLE
Confused about bootloader and the flow of running programs on FPGA

### ISSUE THREAD

**Issue by buctor41** [MaxXSoft/Fuxi#2]
I'm a little confused about the bootloader(soc/soc.srcs/sources_1/new/ocm.coe),Because it is the form of machine code,i do not know which hardware is booted.And I want to run the CoreMark or other programs on the fpga,what should i do?

**Comment by MaxXSoft** [comment]
## Which hardware is booted?

The source code of the bootloader can be found [here](https://github.com/MaxXSoft/GeeOS/tree/master/src/boot), which you can see the bootloader initializes the UART, detects the status of switch on the FPGA board, and then loads program from the flash or UART.

## How to run programs on the FPGA?

You can compile your **bare-metal** program into an ELF file, write it to the flash memory, then turn the switch on the FPGA board to *flash boot mode* (see the bootloader implementation), and finally reset the FPGA.

You can also turn the switch to *UART boot mode*, connect the serial port of FPGA to your PC, and then use [this script](https://github.com/MaxXSoft/GeeOS/blob/master/utils/uart.py) to send the ELF file to the board.

Some of ready-to-run programs (including CoreMark) can be found [here](https://github.com/MaxXSoft/Fuxi-Soft).
